# Generated by Django 3.1.7 on 2021-05-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210517_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(default='NEW PRODUCT', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('SW', 'SportWear'), ('S', 'Shirt'), ('Ow', 'OutWear')], max_length=2),
        ),
    ]
