# Generated by Django 3.1.7 on 2021-05-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20210518_2129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('SW', 'SportWear'), ('Ow', 'OutWear'), ('S', 'Shirt')], default='S', max_length=2),
            preserve_default=False,
        ),
    ]
