# Generated by Django 3.1.7 on 2021-06-10 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_auto_20210610_0708'),
    ]

    operations = [
        migrations.DeleteModel(
            name='brans',
        ),
    ]
