# Generated by Django 3.1.7 on 2021-06-10 02:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_auto_20210610_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='checkout_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='email',
            field=models.CharField(blank=True, max_length=50, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='bill',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='bill',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='phone'),
        ),
    ]
