# Generated by Django 3.1.7 on 2021-06-10 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0043_auto_20210610_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='name'),
        ),
    ]
