# Generated by Django 3.1.7 on 2021-06-10 02:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0045_auto_20210610_0911'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bill',
            new_name='Bills',
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('D', 'danger'), ('S', 'secondary'), ('P', 'primary')], max_length=2),
        ),
    ]
