# Generated by Django 3.1.7 on 2021-06-10 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0047_auto_20210610_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='order',
        ),
        migrations.AddField(
            model_name='bills',
            name='order',
            field=models.ManyToManyField(to='catalog.OrderItem'),
        ),
    ]
