# Generated by Django 3.1.7 on 2021-06-10 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0049_auto_20210610_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='order',
        ),
        migrations.AddField(
            model_name='bills',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('D', 'danger'), ('P', 'primary'), ('S', 'secondary')], max_length=2),
        ),
    ]
