# Generated by Django 3.1.7 on 2021-06-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0053_auto_20210610_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='billsdetail',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('S', 'secondary'), ('D', 'danger'), ('P', 'primary')], max_length=2),
        ),
    ]
