# Generated by Django 3.1.7 on 2021-06-10 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0054_auto_20210610_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='order',
        ),
    ]
