# Generated by Django 3.1.7 on 2021-06-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0055_remove_bills_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('D', 'danger'), ('S', 'secondary'), ('P', 'primary')], max_length=2),
        ),
    ]
