# Generated by Django 3.1.7 on 2021-06-10 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0057_auto_20210610_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='items',
        ),
        migrations.AddField(
            model_name='billsdetail',
            name='bill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.bills'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], max_length=2),
        ),
    ]
