# Generated by Django 3.1.7 on 2021-06-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0060_auto_20210611_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('B', 'Black'), ('S', 'Secondary'), ('P', 'Primary'), ('W', 'White'), ('D', 'Danger')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('N', 'NEW'), ('O', 'OLD')], max_length=20),
        ),
    ]
