# Generated by Django 3.1.7 on 2021-06-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0061_auto_20210611_0145'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Brand',
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('B', 'Black'), ('P', 'Primary'), ('W', 'White'), ('D', 'Danger'), ('S', 'Secondary')], max_length=2),
        ),
    ]
