# Generated by Django 3.1.7 on 2021-06-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0062_auto_20210611_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': 'Brand'},
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('B', 'Black'), ('D', 'Danger'), ('S', 'Secondary'), ('P', 'Primary'), ('W', 'White')], max_length=2),
        ),
    ]
