# Generated by Django 3.1.7 on 2021-06-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0063_auto_20210611_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='brand',
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('O', 'OLD'), ('N', 'NEW')], max_length=20),
        ),
    ]
