# Generated by Django 3.1.7 on 2021-06-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0064_auto_20210611_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('S', 'Secondary'), ('D', 'Danger'), ('P', 'Primary'), ('P', 'Pink'), ('B', 'Black'), ('W', 'White')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('N', 'NEW'), ('O', 'OLD')], max_length=20),
        ),
    ]
